# Proprietary (c) Ryan Walsh / Walsh Tech Group
# All rights reserved. Professional preview only.

class ProviderError(Exception):
    def __init__(self, provider: str, message: str):
        self.provider = provider
        super().__init__(f"[{provider}] {message}")


class ProviderAuthError(ProviderError): ...
class ProviderRateLimitError(ProviderError): ...
class ProviderUnavailableError(ProviderError): ...
class ProviderSchemaError(ProviderError): ...
class ProviderDataGapError(ProviderError): ...
